# Generated by Django 4.2.2 on 2023-08-10 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0003_remove_postinfo_height_remove_postinfo_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinfo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
