# Generated by Django 4.2.2 on 2023-08-10 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0004_postinfo_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinfo',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='post_dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
